export interface ConfigurationFileInterface {
    output: string;
    extTheme: string;
    language: string;
    theme: string;
    name: string;
    assetsFolder: string;
    open: boolean;
    toggleMenuItems;
    templates: string;
    navTabConfig;
    includes;
    includesName: string;
    silent: boolean;
    serve;
    host: string;
    port: number;
    watch: boolean;
    exportFormat: string;
    jsonIndent: number;
    multiVersion: boolean;
    versionLabel: string;
    versionsRoot: string;
    maxVersionsShown: number;
    hideGenerator: boolean;
    hideDarkModeToggle: boolean;
    coverageTest: number;
    coverageMinimumPerFile: number;
    coverageTestThresholdFail: string;
    coverageTestShowOnlyFailed: boolean;
    unitTestCoverage: string;
    disableSourceCode: boolean;
    disableDomTree: boolean;
    disableTemplateTab: boolean;
    disableStyleTab: boolean;
    disableGraph: boolean;
    disableCoverage: boolean;
    disablePrivate: boolean;
    disableProtected: boolean;
    disableInternal: boolean;
    disableLifeCycleHooks: boolean;
    disableConstructors: boolean;
    disableRoutesGraph: boolean;
    disableSearch: boolean;
    disableDependencies: boolean;
    disableDependenciesTab: boolean;
    disablePlaygroundTab: boolean;
    strictPlaygrounds: boolean;
    disableProperties: boolean;
    disableFilePath: boolean;
    disableOverview: boolean;
    showEffects: boolean;
    minimal: boolean;
    customFavicon: string;
    customLogo: string;
    gaID: string;
    tsconfig: string;
    files;
    exclude;
    include;
    publicApiOnly: string;
    infoTabSections: string[];
    apiTabSections: string[];
    themingTabSections: string[];
    stackblitz: boolean;
    stackblitzTemplate: string;
    playgroundMaterialShell: boolean;
    playgroundDepDepth: number;
    playgroundFileCountCap: number;
    playgroundFileCap: number;
    playgroundHead: string[];
    playgroundGlobalStyles: string;
    playgroundVendor: string[];
    playgroundVendorRoot: string;
    playgroundVendorCap: number;
    playgroundVendorIncludeSourcemaps: boolean;
    menuLayout: 'type' | 'feature';
    features: Record<string, string>;
    featureContainers: string[];
    featureUtilityFolders: string[];
    featureRoleFolders: string[];
    collapsedAll: boolean;
    shikiTheme: string;
}
