import { describe, expect, it } from 'vitest';
import {
    EXPORT_SCHEMA_VERSION,
    type ExportData
} from '../../../src/app/interfaces/export-data.interface';
import { emitLlmMd, renderLlmMd } from '../../../src/llm-md';

const baseExport = (overrides: Partial<ExportData> = {}): ExportData => ({
    schemaVersion: EXPORT_SCHEMA_VERSION,
    generatedAt: '2026-04-01T00:00:00.000Z',
    compodocxVersion: '0.3.0',
    components: [],
    pipes: [],
    modules: [],
    directives: [],
    injectables: [],
    guards: [],
    interceptors: [],
    classes: [],
    interfaces: [],
    ...overrides
});

describe('llm-md/dispatcher — emitLlmMd', () => {
    it('emits the project header with name, description, version and timestamp', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '2026-04-01T00:00:00.000Z', compodocxVersion: '0.3.0' },
            options: { projectName: 'My App', projectDescription: 'A widget' },
            data: baseExport()
        });
        expect(out).toContain('# My App');
        expect(out).toContain('> A widget');
        expect(out).toContain('> Generated by compodocx 0.3.0 at 2026-04-01T00:00:00.000Z');
    });

    it('omits empty entity sections', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'Empty' },
            data: baseExport()
        });
        expect(out).not.toContain('## Modules');
        expect(out).not.toContain('## Components');
        expect(out).not.toContain('## Pipes');
    });

    it('emits a Components section when components exist', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'X' },
            data: baseExport({
                components: [{ name: 'FooComponent', selector: 'app-foo' }]
            })
        });
        expect(out).toContain('## Components');
        expect(out).toContain('### FooComponent');
        expect(out).toContain('Selector: `app-foo`');
    });

    it('always ends with exactly one trailing newline', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'X' },
            data: baseExport()
        });
        expect(out.endsWith('\n')).toBe(true);
        expect(out.endsWith('\n\n')).toBe(false);
    });

    it('renders miscellaneous functions, type aliases, enumerations and variables', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'X' },
            data: baseExport({
                miscellaneous: {
                    functions: [{ name: 'createId', returnType: 'string' }],
                    typealiases: [{ name: 'Id', rawtype: 'string' }],
                    enumerations: [{ name: 'Status', childs: [{ name: 'On' }] }],
                    variables: [{ name: 'PI', type: 'number', defaultValue: '3.14' }]
                }
            })
        });
        expect(out).toContain('## Public functions');
        expect(out).toContain('## Public type aliases');
        expect(out).toContain('## Public enumerations');
        expect(out).toContain('## Public variables');
    });

    it('renders a Public tokens section after Public functions', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'X' },
            data: baseExport({
                miscellaneous: { functions: [{ name: 'createId', returnType: 'string' }] },
                tokens: [{ name: 'ApiUrl', isToken: true, tokenType: 'string' }]
            })
        });
        expect(out).toContain('## Public tokens');
        expect(out).toContain('### ApiUrl');
        expect(out).toContain('Token type: `string`');
        expect(out.indexOf('## Public functions')).toBeLessThan(out.indexOf('## Public tokens'));
    });

    it('skips symbols that reach no public entry point in every section', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'X' },
            data: baseExport({
                components: [
                    { name: 'ShownComponent' },
                    { name: 'HiddenComponent', notExported: true }
                ],
                tokens: [{ name: 'HIDDEN_TOKEN', isToken: true, notExported: true }],
                miscellaneous: {
                    functions: [{ name: 'shownFn' }, { name: 'hiddenFn', notExported: true }],
                    variables: [{ name: 'HIDDEN_CONST', notExported: true }]
                }
            })
        });
        expect(out).toContain('### ShownComponent');
        expect(out).toContain('shownFn');
        expect(out).not.toContain('HiddenComponent');
        expect(out).not.toContain('hiddenFn');
        expect(out).not.toContain('## Public tokens');
        expect(out).not.toContain('## Public variables');
    });

    it('escapes special characters in the project name', () => {
        const out = emitLlmMd({
            meta: { generatedAt: '', compodocxVersion: '' },
            options: { projectName: 'My *Awesome* `App`' },
            data: baseExport()
        });
        expect(out).toContain('# My \\*Awesome\\* \\`App\\`');
    });
});

describe('llm-md/dispatcher — renderLlmMd', () => {
    it('builds the meta envelope from ExportData header fields', () => {
        const data = baseExport({
            generatedAt: '2026-05-08T10:00:00.000Z',
            compodocxVersion: '0.3.1'
        });
        const out = renderLlmMd(data, { projectName: 'X' });
        expect(out).toContain('Generated by compodocx 0.3.1 at 2026-05-08T10:00:00.000Z');
    });

    it('treats missing volatile header fields as empty strings', () => {
        const data: ExportData = {
            schemaVersion: EXPORT_SCHEMA_VERSION,
            generatedAt: '',
            compodocxVersion: ''
        };
        const out = renderLlmMd(data, { projectName: 'X' });
        // header line is still emitted, just without a version/at suffix
        expect(out).toContain('Generated by compodocx');
    });
});
