import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { marked } from 'marked';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

/**
 * Real-fixture smoke against todomvc-ng2. Spawns the CLI to assert that
 * `--exportFormat llm-md`:
 *   - writes a `llm-context.md` file when -d is provided
 *   - streams to stdout (and progress logs to stderr) when -d is omitted
 *   - produces markdown that `marked.parse()` accepts
 *   - keeps the output under a sane size cap (no unbounded base64 bloat)
 *
 * The build runs once per test file via `pretest:unit` (npm test:unit
 * triggers a full build), so `bin/index-cli.js` is up-to-date when this
 * spec executes locally and in CI.
 */

const REPO_ROOT = path.resolve(__dirname, '../../..');
const CLI = path.join(REPO_ROOT, 'bin', 'index-cli.js');
const FIXTURE_TSCONFIG = path.join(
    REPO_ROOT,
    'test',
    'fixtures',
    'todomvc-ng2',
    'src',
    'tsconfig.json'
);

const tmpDir = path.join(os.tmpdir(), `compodocx-llm-md-${Date.now()}`);

const runCli = (args: string[]) =>
    spawnSync('node', [CLI, ...args], {
        cwd: REPO_ROOT,
        encoding: 'utf8',
        env: { ...process.env, NO_COLOR: '1' }
    });

beforeAll(() => {
    fs.mkdirSync(tmpDir, { recursive: true });
});

afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
});

const skipIfBuildMissing = !fs.existsSync(CLI);

describe.skipIf(skipIfBuildMissing)('llm-md/fixture — todomvc real-fixture', () => {
    it('writes <output>/llm-context.md when -d is provided', () => {
        const outDir = path.join(tmpDir, 'with-output');
        const result = runCli(['-p', FIXTURE_TSCONFIG, '--exportFormat', 'llm-md', '-d', outDir]);
        expect(result.status).toBe(0);
        const filePath = path.join(outDir, 'llm-context.md');
        expect(fs.existsSync(filePath)).toBe(true);
        const content = fs.readFileSync(filePath, 'utf8');
        expect(content.length).toBeGreaterThan(1000);
        expect(content).toMatch(/^# /);
    });

    it('streams markdown to stdout when -d is omitted', () => {
        const result = runCli(['-p', FIXTURE_TSCONFIG, '--exportFormat', 'llm-md']);
        expect(result.status).toBe(0);
        // Markdown payload on stdout
        expect(result.stdout).toMatch(/^# /);
        expect(result.stdout).toContain('## Components');
        // Progress logs on stderr
        expect(result.stderr.length).toBeGreaterThan(0);
        expect(result.stderr).toMatch(/Using tsconfig file/);
        // Banner suppressed
        expect(result.stdout).not.toMatch(/TypeScript version used by Compodoc/);
        expect(result.stdout).not.toMatch(/Operating system/);
    });

    it('produces markdown that marked.parse() accepts without throwing', () => {
        const outDir = path.join(tmpDir, 'parse-check');
        const result = runCli(['-p', FIXTURE_TSCONFIG, '--exportFormat', 'llm-md', '-d', outDir]);
        expect(result.status).toBe(0);
        const content = fs.readFileSync(path.join(outDir, 'llm-context.md'), 'utf8');
        expect(() => marked.parse(content)).not.toThrow();
    });

    it('output stays under 200 KB for todomvc (token-density sanity check)', () => {
        const outDir = path.join(tmpDir, 'size-check');
        const result = runCli(['-p', FIXTURE_TSCONFIG, '--exportFormat', 'llm-md', '-d', outDir]);
        expect(result.status).toBe(0);
        const stat = fs.statSync(path.join(outDir, 'llm-context.md'));
        expect(stat.size).toBeLessThan(200 * 1024);
    });

    it('contains the canonical entity sections for todomvc fixture', () => {
        const outDir = path.join(tmpDir, 'sections-check');
        const result = runCli(['-p', FIXTURE_TSCONFIG, '--exportFormat', 'llm-md', '-d', outDir]);
        expect(result.status).toBe(0);
        const content = fs.readFileSync(path.join(outDir, 'llm-context.md'), 'utf8');
        expect(content).toContain('## Components');
        expect(content).toContain('### AppComponent');
        // schemaVersion / generated marker present
        expect(content).toMatch(/Generated by compodocx \S+ at \S+/);
    });

    it('cross-platform path normalization on the output file path', () => {
        const outDir = path.join(tmpDir, 'cross-platform');
        const result = runCli(['-p', FIXTURE_TSCONFIG, '--exportFormat', 'llm-md', '-d', outDir]);
        expect(result.status).toBe(0);
        const filePath = path.join(outDir, 'llm-context.md');
        const normalized = filePath.split(path.sep).join('/');
        expect(normalized.endsWith('/llm-context.md')).toBe(true);
    });
});
