/**
 * `--exportFormat llm-md` dispatcher.
 *
 * Walks every entity bucket of an `ExportData` snapshot and concatenates the
 * per-kind markdown into a single string. Pure-functional: the dispatcher
 * does not touch the filesystem and never logs. The CLI consumer decides
 * whether to write to disk or stream to stdout.
 *
 * Architectural mirror of `src/diff/compare.ts`: a runtime bucket list
 * followed by a kind-specific switch. Adding a new entity kind to
 * `ExportData` means adding one bucket entry and one emit function — no other
 * code path needs to change.
 */

import type {
    ExportData,
    ExportEnumeration,
    ExportFunction,
    ExportSemanticFacts,
    ExportTypeAlias,
    ExportVariable
} from '../app/interfaces/export-data.interface';
import {
    emitClass,
    emitComponent,
    emitDirective,
    emitEnumeration,
    emitFunction,
    emitGuard,
    emitInjectable,
    emitInterceptor,
    emitInterface,
    emitPipe,
    emitTypeAlias,
    emitVariable
} from './emit';
import { collapseDescription, escapeMarkdown, joinSections } from './format';
import type { LlmMdEmitOptions, LlmMdInput, LlmMdSnapshotMeta } from './types';

const sectionHeader = (title: string): string => `## ${title}`;

/** Symbols that reach no public entry point are left out of every section. */
const documented = <T extends ExportSemanticFacts>(items: ReadonlyArray<T> | undefined): T[] =>
    (items ?? []).filter(item => item.notExported !== true);

const renderSection = <T extends ExportSemanticFacts>(
    title: string,
    items: ReadonlyArray<T> | undefined,
    emit: (item: T) => string
): string => {
    const blocks = documented(items)
        .map(emit)
        .filter(s => s.length > 0);
    if (blocks.length === 0) {
        return '';
    }
    return `${sectionHeader(title)}\n\n${blocks.join('\n\n')}`;
};

const renderListSection = <T extends ExportSemanticFacts>(
    title: string,
    items: ReadonlyArray<T> | undefined,
    emit: (item: T) => string
): string => {
    const lines = documented(items)
        .map(emit)
        .filter(s => s.length > 0);
    if (lines.length === 0) {
        return '';
    }
    return `${sectionHeader(title)}\n\n${lines.join('\n')}`;
};

const buildHeader = (meta: LlmMdSnapshotMeta, options: LlmMdEmitOptions): string => {
    const lines = [`# ${escapeMarkdown(options.projectName)}`];
    if (options.projectDescription) {
        const collapsed = collapseDescription(options.projectDescription);
        if (collapsed) {
            lines.push('', `> ${escapeMarkdown(collapsed)}`);
        }
    }
    const versionPart = meta.compodocxVersion ? ` ${meta.compodocxVersion}` : '';
    const generatedPart = meta.generatedAt ? ` at ${meta.generatedAt}` : '';
    lines.push('', `> Generated by compodocx${versionPart}${generatedPart}, llm-md export.`);
    return lines.join('\n');
};

/**
 * Run every emit function and concatenate. Output ends with a single trailing
 * newline so file writes leave a clean line at EOF and stdout pipes don't
 * stick the next prompt onto the last section.
 */
export const emitLlmMd = (input: LlmMdInput): string => {
    const { meta, options, data } = input;
    const misc = data.miscellaneous;

    const sections: string[] = [
        buildHeader(meta, options),
        renderSection('Components', data.components, emitComponent),
        renderSection('Directives', data.directives, emitDirective),
        renderSection('Pipes', data.pipes, emitPipe),
        renderSection('Services / Injectables', data.injectables, emitInjectable),
        renderSection('Guards', data.guards, emitGuard),
        renderSection('Interceptors', data.interceptors, emitInterceptor),
        renderSection('Classes', data.classes, emitClass),
        renderSection('Interfaces', data.interfaces, emitInterface),
        renderListSection<ExportFunction>('Public functions', misc?.functions, emitFunction),
        renderSection('Public tokens', data.tokens, emitInjectable),
        renderListSection<ExportTypeAlias>('Public type aliases', misc?.typealiases, emitTypeAlias),
        renderSection<ExportEnumeration>(
            'Public enumerations',
            misc?.enumerations,
            emitEnumeration
        ),
        renderListSection<ExportVariable>('Public variables', misc?.variables, emitVariable)
    ];

    return `${joinSections(sections)}\n`;
};

/**
 * Build the `LlmMdInput` envelope from a parsed `ExportData` and emit. Helper
 * for callers that only have the raw export shape (CLI path) and don't want
 * to construct the meta themselves.
 */
export const renderLlmMd = (data: ExportData, options: LlmMdEmitOptions): string => {
    const meta: LlmMdSnapshotMeta = {
        generatedAt: data.generatedAt ?? '',
        compodocxVersion: data.compodocxVersion ?? ''
    };
    return emitLlmMd({ meta, options, data });
};

export type { LlmMdEmitOptions, LlmMdInput, LlmMdSnapshotMeta } from './types';
